export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';


export enum CategoryActionTypes {
    FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST',
    FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE',
}